version: '3.5'

services:
  griddb:
    #image: griddbnet/griddb
    build:
      context: ./griddb
      dockerfile: Dockerfile
    ports:
      - "10001:10001"
      - "10010:10010"
      - "10020:10020"
      - "10030:10030"
      - "10040:10040"
      - "10050:10050"
      - "10080:10080"
      - "20001:20001"
  zeppelin:
    build:
      context: ./zeppelin
      dockerfile: Dockerfile
    image: apache/zeppelin:0.9.0
    volumes:
      - ./notebook:/notebook
    ports:
      - "8080:8080"
    environment:
      ZEPPELIN_NOTEBOOK_DIR: '/notebook'